# Tensors

Mathematically, a tensor is a concept of a datastructure that can hold data in a variety of ways. it can hold a scalar, a string, or the most usual case a multidimensional array.

In tensorflow, a tensor can be created as either a constant or a variable.

## Variables

To create a vairable, you use the `tf.Variable` class like this:

```python
x = tf.Variable(3.0) # x is a variable that holds a scalar of 3.0
```

Here 3.0 is refered to as the `inital_value`.it's important to note the dimensionality of the variable, while we now have a scaler, we can also have a vector, matrix, or event list of strings; so usually you will pass two additional arguments to the `tf.Variable` constructor: the shape of the tensor, and data type of its individual values, while they can be infered from the `initial_value` if not specified, it's usually best to specify them explicitly, specially the data type.

```python
x = tf.Variable([2, 3], shape=(2,) ,dtype=tf.float32) # x is a variable that holds a vector of 2 elements, of type float32
```

usually we wouldn't pass shape since it can be inferred from the `initial_value` if not specified, but it's best to specify it to make sure the shape of initial_value is what you expect and nothing else. shape errors are very common with tensorflow. if a mismatch occurs, it will raise an error.

The `shape` is not just there for semantic reasons only, it can be used to set the dimensionality of a tensor to be unknown, by `shape=tf.TensorShape(None)`. which can be useful for some cases.

You can read the value stored in a variable by using `tensor.read_value().numpy()`

## Constants

They are tensors whose values can't be changed, they are created using `tf.constant` with an initial (and final) value.

```python
c = tf.constant(3.0) # c is a constant tensor with value 3.0
```

Unlike Variables, declaring constants is more flexible, for example: the shape provided is used to reshape the given value if possible.

```python
c = tf.constant([1, 2, 3, 4, 5, 6], shape=(2,3)) # c is a matrix of shape (2,3), for variables this would cause an error
# > [[1, 2, 3],[4, 5, 6]]
```

and if the given value is a scaler, it will be broadcasted to the shape, so:

```python
c = tf.constant(3.0, shape=(3,3)) # c is a matrix of shape (3, 3) with all elements equal 3.0
# > [[3, 3, 3],[3, 3, 3],[3, 3, 3]]
```



In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# autoreload
%load_ext autoreload
%autoreload 2

Variables are important since there are used to hold the weights, biases, inputs and outputs of a neural network. variables can be marked as `trainable` or not, depending on how you want to optimize the model, and we already saw this in action while creating a [custom model](./custom_model.ipynb).

To access the weights of a model you can use: `model.weights` or `model.variables`.

In [3]:
from simple_model import get_simple_regression_model

model = get_simple_regression_model()

print(model.variables)                  # print all variables

print(model.trainable_variables)        # print all trainable variables, all in this case

print(model.non_trainable_variables)    # print all non-trainable variables, none in this case

print(model.weights)                    # print all variables

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.2279576]], dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]
[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.2279576]], dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]
[]
[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.2279576]], dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


# Operations on Tensors

Tensors support all operations you need, you may think you would need to: read the value in the tensor, mutate it, then reasign it, but you don't, Tensorflow provides functions to apply operations on tensors, like `tf.add`, `tf.subtract`, `tf.multiply`, ... etc. it's just like using numpy, it even supports broadcasting.

```python
tf.add([1, 2, 3], [4, 5, 6]) # > tf.Tensor([5, 7, 9], shape=(3,), dtype=int32)
```

one very useful operation is `tf.cast` which is used to change the data type held by the tensor.
Tensorflow also supports operator overloading, so you can do the samething like this.

```python
tf.Tensor([1, 2, 3]) + tf.Tensor([4, 5, 6]) # > tf.Tensor([5, 7, 9], shape=(3,), dtype=int32)
```

## Compatability with Numpy

Tensors can be passed to numpy functions, so you can do the samething like this:

```python
a = tf.Tensor([1, 2, 3])
b = np.array([4, 5, 6])
np.multiply(a, b) # > [4, 10, 18]
```

The tensors are first evaluted as numpy arrays and then the operation is done.

It also goes the other way around, numpy arrays can be passed to tensorflow functions, and the result is a tensor, you can use `tensor.numpy()` to access the numpy array within.


# Examples

In [4]:
# Create a 1D uint8 NumPy array comprising of first 25 natural numbers
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
# Convert NumPy array to Tensor using `tf.constant`
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [6]:
# Square the input tensor x
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [7]:
# Reshape tensor x into a 5 x 5 matrix. 
x = tf.reshape(x, (5, 5))
x

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

In [8]:
# Cast tensor x into float32. Notice the change in the dtype.
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [9]:
# Let's define a constant and see how broadcasting works in the following cell.
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [10]:
# Multiply tensor `x` and `y`. `y` is multiplied to each element of x.
result = tf.multiply(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

In [11]:
# Now let's define an array that matches the number of row elements in the `x` array.
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [12]:
# Add tensor `x` and `y`. `y` is added element wise to each row of `x`.
result = x + y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>